version: "3.11"
networks:
    default:
        name: chat-network
        external: true
services:
    ads-chat-api-service:
        image: ads-chat-api-service
        container_name: ads-chat-api-service
        ports:
            - 9000:9000
        volumes:
            - ../chat_api:/app
        environment:
            DEV: "1"
        secrets:
            - open_ai_key
            - ads_key
    ads-chat-frontend:
        image: ads-chat-frontend
        container_name: ads-chat-frontend
        ports:
            - 8501:8501
        volumes:
            - ../chat_streamlit:/app
        environment:
            API_SERVICE_URL: "http://ads-chat-api-service:9000"
        depends_on:
            - ads-chat-api-service

secrets:
    open_ai_key:
        file: ../secrets/open_ai_key.txt
    ads_key:
        file: ../secrets/ads_key.txt